### PR TITLE
eu-legal additions

### PR DESCRIPTION
**Pull request by jBangiev**

### CODE REVIEW

**Comment by jBangiev** [comment]
Hi @gaillafr 
what is with this request?

**Comment by Quetzacoalt91** [comment]
Hi @jBangiev,

Sorry for the late reply, I don't how but I missed this PR in the validation process.
Just a small change to suggest, maybe we could add a common function for hookDisplayPaymentEU and hookPayment ? Something like:
```php
public function hasProductDownload()
{
	foreach ($params['cart']->getProducts() AS $product)
	{
		$pd = ProductDownload::getIdFromIdProduct((int)($product['id_product']));
		if ($pd AND Validate::isUnsignedInt($pd))
			return false;
	}
}
```

**Comment by jBangiev** [comment]
Hi,
I've changed it.

**Comment by Quetzacoalt91** [comment]
Hi @jBangiev,

Thanks a lot, I pushed the PR on the dev branch for the next release. It will be opened till we merge it on the master branch.

**Comment by Quetzacoalt91** [comment]
Hi,

This PR has been merged for the version 0.7.4 of CashOnDelivery.

Regards

**Pull request merged**
